version: '3'

services:
  samba:
    build: .
    ports:
      - "139:139"
      - "445:445"
    volumes:
      #      - ./samba_config/smb.conf:/etc/samba/smb.conf
      - ./compartilhamento:/compartilhamento
    restart: always

