version: '3'

services:
  samba:
    entrypoint: entrypoint.test.sh
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./SambaWebAPI:/SambaWeb/SambaWebAPI
