version: '3'

services:
  samba:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "139:139"
      - "445:445"
      - "8080:8080"
    volumes:
      - ./SambaWebAPI:/SambaWeb/SambaWebAPI
