version: "3"

services:
  samba:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
    ports:
      - "139:139"
      - "445:445"
      - "8080:8080"
    volumes:
      - ./:/SambaWeb

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SambaWeb
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'  -p 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-user.sql:/docker-entrypoint-initdb.d/init-user.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

volumes:
  postgres-data:
