name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Run tests
        run: |
          cd SambaWebAPI
            ./gradlew test
          
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ../../SambaWebAPI/build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true
